Fix %freeze/%melt{-new}
racket/racklog pull request #21
Opened 2022-02-21 22:21 UTC by jjgriego

I am not sure if this is how they were originally envisioned to work, but I
found it surprising that they (at present) do not really support freezing terms
where there are free variables inside and you don't know where; I was only able
to get them to behave when each variable is always explicitly named in the
terms passed to %freeze and %melt, e.g.

    (%freeze (list X Y Z) (list *X *Y *Z))
    (%melt (list *X *Y *Z) (list A B C))

works just fine, but:

    (%freeze (list X Y Z) F)
    (%melt F (list A B C))

results in A, B, C getting bound to `<frozen>` structs, and not the original
variables. This is because the frozen struct gets folded into the overall term
F and will not be recognized as a `frozen-logic-var?` there.

---

The fix I'm proposing here is to represent frozen variables as `(make-frozen
<logic var>)` directly and then look for the `frozen?` structure in the
procedures that care about frozen terms. This has the special convenience that
in the rest of "unify.rkt", `frozen?` terms will now be recognized as `atom?`
which has the behavior we want anyways.

I added some tests to this effect; all but the first two would fail without the
corresponding changes to "unify.rkt".

A small style note: I opted not to add `frozen?` to `uni-match` since only the
triple (freeze,melt,melt-new) actually want to treat these differently from
`atom?`s

2022-02-22 15:47 UTC, jeapostrophe requested changes
I like this a lot. The code feels simpler and more powerful. Can you take a few of your examples about update the documentation with examples as well, so that we can explicitly say that it has this behavior? The code is very "historical" so I want to be really explicit in the docs about how it differs (in good ways) from ancient examples from the 80s using the same techniques.

2022-02-23 03:47 UTC, jjgriego commented
I added some examples to the docs, but, for whatever it's worth, I checked and this functionality worked as tested here in the past, so there shouldn't really be anything new. I think the rewrite in 1f19edd7c8f10ec7da471eacfa50519f4d1fc535
broke %freeze, etc., as the new tests pass on the commit before that.

2022-02-23 11:17 UTC, jeapostrophe approved these changes

2022-02-23 11:17 UTC, merged

2022-02-23 11:18 UTC, jeapostrophe commented
Awesome!